title: BangPypers Assets
description: All the BangPypers assets in one place. Please follow branding guidelines before using.

theme: jekyll-theme-cayman

meetup_url: https://www.meetup.com/bangpypers

social:
    twitter: https://twitter.com/__bangpypers__
